# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hacktoberfest2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Hacktoberfest2020
  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireImage', '~> 4.1'
  pod 'SwiftyJSON'
  pod 'SwiftLoader', :git => 'https://github.com/ahmednour25689/SwiftLoader.git', :branch => 'master'
  
end
