# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'Hacktoberfest2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hacktoberfest2020
  pod 'CLTypingLabel', '~> 0.4.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'  
end
