# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hacktoberfest2020' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hacktoberfest2020
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Auth'

end
